### ISSUE TITLE
Project's license

### ISSUE THREAD

**Issue by pargue** [alexanderchuranov/Metaresc#1]
Interesting project. Wasn't able to find info about it, but for those looking into using it, what's the project's license?

**Comment by hnarkaytis** [comment]
You may assume that project is published under GPL2.1 just because it uses red/black tree code from glibc https://github.com/alexanderchuranov/Metaresc/blob/8f398e261c6c37c954ed22a6caf1e2dd3cd8fad2/src/mr_tsearch.c

Probably I need to add an explicit notice about license.

HHN.

**Comment by hnarkaytis** [comment]
All GPL code is replaced on genuine implementation. License changed to MIT.

HHN.
