### ISSUE TITLE
TEST_PERFORMANCE tests fail / get flaky when running the test suite in container with resource constraints

### ISSUE THREAD

**Issue by enter-github-username** [alexanderchuranov/Metaresc#10]
Hey,

this is not really an actionable issue, but more an FYI, as this may be correct behavior.

While executing the test suite of metaresc in a podman container, restricted to 10 percent cpu time of an 64 core AMD EPYC 7713 CPU via cpu.cfs_quota_us, all the TEST_PERFORMANCE tests start to become flaky. The log files contain e.g. in the case of `perf_xml1`:

```
Running suite(s): main
0%: Checks: 1, Failures: 1, Errors: 0
perf_xml1.c:3:F:performance test:test_performance:0: performance issue for method XML1 163222 / 16763 = 9.7
FAIL perf_xml1 (exit status: 1)
```

I think this might not only be caused by the restriction of resources, causing `double_time` to be bigger than ´base_time * 5 / 2´, but possibly by CLOCKS_PER_SEC not being accurate when using cpu.cfs_quota_us. This should not be a problem for most users, but it may cause the tests to fail in CI environments, which may use such restrictions for their containers.

As said, this is more an FYI than an actionable real issue. :-)

**Comment by hnarkaytis** [comment]
It's a well known issue. Any virtualised or CPU-bound environment will have the same issue. You just need to skip performance tests in that case. Use flag --without-perftest for [configure](https://github.com/alexanderchuranov/Metaresc/blob/master/configure.ac#L91). Examples could be found [here](https://github.com/alexanderchuranov/Metaresc/blob/master/.github/workflows/test.yml#L43)
