### ISSUE TITLE
MacOS build failed

### ISSUE THREAD

**Issue by zzj1213** [alexanderchuranov/Metaresc#12]
Error:

mr_message.c:120:8: error: call to undeclared library function 'free' with type 'void (void *)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
              free (strings);

**Comment by hnarkaytis** [comment]
Indeed stdlib.h was not included into mr_message.c. I'm puzzled why CI passing ok on all platforms.
Fix merged here https://github.com/alexanderchuranov/Metaresc/commit/ff02ea5f319742d9419904da203d3b3bd44c3565
