### ISSUE TITLE
Write serialized XML to string/buffer

### ISSUE THREAD

**Issue by aniruddha-a** [alexanderchuranov/Metaresc#6]
Hello,

I see that Metaresc has

```
MR_PRINT(..)  and
MR_FPRINT
```

But there doesn't seem to be a `MR_SPRINT` to write to a string - is that correct  ?
So, if I want to serialize into a buffer, should I use the usual unix tricks (`freopen`?)
or there is some other API of Metaresc that I am missing?

Thanks.

**Comment by hnarkaytis** [comment]
MR_PRINT is just a fancy wrapper around serialization to string. The main purpose of this macro is to hide all boiler plate code with NULL checking. 
For serialization to strings you need MR_SAVE_*() macro family. For XML specifically - MR_SAVE_XML (type, pointer)
Sample below:

```
#include <metaresc.h>

TYPEDEF_STRUCT (mr_div_t,
                int rem,
                int quot,
                );

int main ()
{
  mr_div_t div = {1, 2};
  char * xml = MR_SAVE_XML (mr_div_t, &div);
  if (xml)
    {
      printf ("xml = %s", xml);
      MR_FREE (xml);
    }
  return (EXIT_SUCCESS);
}
```
The out is:
```
xml = <?xml version="1.0"?>
<div>
  <rem>1</rem>
  <quot>2</quot>
</div>
```

Serialization/deserialization to/from XML has 2 options: MR_SAVE_XML2/MR_LOAD_XML2 uses libxml2, and MR_SAVE_XML1/MR_LOAD_XML1 uses custom implementation. MR_SAVE_XML/MR_LOAD_XML is just a redirect to the first available option (XML2 is a default).

**Comment by aniruddha-a** [comment]
Awesome! Thank you.

And, thanks for Metaresec.
