### ISSUE TITLE
Build with clang on native Windows

### ISSUE THREAD

**Issue by escherstair** [alexanderchuranov/Metaresc#8]
Is it possible building metaresc on native Windows (i.e., no msys2, no cygwin) with clang?
Is it necessary some preliminary step?

I'm worried about `mr_pp.sh`, `cinit_load.y`, `mr_export.h.in`, ... that I think are handled in some special ways (scripts or similar).

**Comment by escherstair** [comment]
I see that clang on windows works in CI and this is good news.
And I see [here](https://github.com/alexanderchuranov/Metaresc/actions/runs/4406343831/jobs/7718461385) that the job to build the library is long.
You wrote about compiled binaries + headers. Is there a link where I can download them (for clang on Windows)?

**Comment by hnarkaytis** [comment]
Build on CI is long because it runs in VM. Build on M1 takes only 15 sec.

I added archiving of artefacts to CI. Now you could download static library and all required header files for Windows builds.
Sample here https://github.com/alexanderchuranov/Metaresc/suites/11561742085/artifacts/598812722

**Comment by hnarkaytis** [comment]
@escherstair do you think we can close this issue?

**Comment by escherstair** [comment]
Yes.
I see that the build works as expected.
Unfortunately I cannot use the build artifacts because my compiler is a customized old release of clang (3.3) and it lacks of some features.
And it has no sense asking someone to support this specific compiler.

Thanks

**Comment by escherstair** [comment]
Not sure about a simple fix.
As an example, my compiler doesn't have `<complex.h>` and other include files.
So the (first) big problem is this one.
I had exactly the same issue while trying to integrate libraries.
The workaround that usually works is building the library with gcc (or clang) into a dll.
Then I create a dll wrapper that exposes a subset of all its functions (only those I need) and that has a header file that includes only the `.h` files I have with my compiler.
As the last step, my application loads dynamically the dll and the necessary funtions.

But it's a big job, and with a library like metaresc that must access to `typedefs` to be able to serialize the data, I'm not sure that an approach like this can work.

**Comment by hnarkaytis** [comment]
Try the following:
1. In metaresc.h replace дшту 35: #include <complex.h> on #define complex
2. Remove lines 194, 196, 198. 
   | (__builtin_types_compatible_p (complex float SUFFIX, TYPE) ? MR_TYPE_COMPLEX_FLOAT : 0) \
   | (__builtin_types_compatible_p (complex double SUFFIX, TYPE) ? MR_TYPE_COMPLEX_DOUBLE : 0) \
   | (__builtin_types_compatible_p (complex long double SUFFIX, TYPE) ? MR_TYPE_COMPLEX_LONG_DOUBLE : 0) \

Not sure that you need dll wrapper. I would expect that it should work as is.

**Comment by escherstair** [comment]
I did it.
Then I had to undef `#define MR_HAVE_INT128 /**/` because __int128 is not supported on my target.
At this point I have another compilation error:
https://github.com/alexanderchuranov/Metaresc/blob/a1724d4266fce21ba78757f89998a7af798c735d/src/mr_protos.h#L16-L25
```
"mr_protos.h"(16,1)  error: too few arguments provided to function-like macro invocation
note: expanded from macro 'TYPEDEF_ENUM'
note: expanded from macro 'P00_TYPEDEF'
note: expanded from macro 'P00_TYPEDEF_'
note: (skipping 18 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
```
but I didn't find a way to have `-fmacro-backtrace-limit=0` working

**Comment by hnarkaytis** [comment]
@escherstair looks like a some critical feature lack. The odd thing here is that declaration above uses the same macroses and worked well. 

Point me on clang package that you use. I'll try to troubleshoot.

**Comment by escherstair** [comment]
[This is](https://www.ni.com/it-it/support/downloads/software-products/download.labwindows-cvi.html#306964) the compiler. It uses a customized clang 3.3 under the hood.
I think you can install it and use in evaluation mode for one week.
But, one more time, I'm not sure it's a good idea wasting time in this way...
I did it so many times in the past..

**Comment by hnarkaytis** [comment]
The version that you use is way too outdated. I can't even install it on latest Windows. 
Closing this issue.
