### ISSUE TITLE
Build is broken on Ubuntu

### ISSUE THREAD

**Issue by sociopart** [alexanderchuranov/Metaresc#9]
Hello!

I'm constantly getting problems with current Metaresc repo.

What did I do:
- Executed all commands from README.md for Ubuntu.

What happened:

During execution of `./configure`, I'm getting error which prevents me from going forward and actually build something.

```
checking uncovered int type... long long
checking size of uncovered int type... 64
checking size of long double... 16
checking size of double... 8
checking long double significant bytes... ./configure: line 13176: syntax error near unexpected token `fi'
./configure: line 13176: `fi'
```

I didn't edit `./configure` just because it's auto-generated. So, what's going wrong?

System Info:
OS: Ubuntu 20.04 
Architecture: 64bit
Compiler: GCC 9.3.0
Automake: v1.16.1
Make: v4.2.1.

P.S. I tried to test it on a Debian VM, got same results.

Thanks in advance!

**Comment by hnarkaytis** [comment]
Fixed in master.
